/* eslint-disable no-unused-vars */
import Character from './Character';
import Bowerman from './Bowerman';
import Daemon from './Daemon';
import Magician from './Magician';
import Swordsman from './Swordsman';
import Undead from './Undead';
import Zombie from './Zombie';
/* eslint-disable no-unused-vars */
